src/pubsub/pubsub-update.js

We wan't to at least ensure that the wathchers list of displayIds
isn't being sent to all displays.

Be explicit about data that is sent to displays

---

src/event-handlers/display-connections.js
src/event-handlers/messages/screenshot-saved.js

The message is coming from player in a different format than what comes from core.

Update screenshot-saved handler

---

src/event-handlers/messages/content-update.js
src/event-handlers/messages/reboot.js
src/event-handlers/messages/restart.js

This avoids potential problems with data coming from core or somewhere else.

Accept did or displayId

---

src/webhooks/presence/set-cors-headers.js

This should fix [apps issue 579](https://github.com/Rise-Vision/rise-vision-apps/issues/579#issuecomment-371948945)
@rudibravo fyi

Allow content-type explicitly for CORS

---

src/gcs.js
src/version-compare/api.js
test/integration/gcs.js
test/integration/watch.js

The file should still be stored in metadata for potential ADD from
pubsub. Response to WATCH will be version "0" with no download token.

Don't throw when WATCH file is not on GCS

---

src/event-handlers/watch-error.js
src/gcs.js
test/integration/folder-watch.js

Fixes an issue when submitting a WATCH on a missing / empty folder and
adds support for both cases so that clients can handle them
specifically.

Add support for missing / empty folders

---

src/db/api.js
src/event-handlers/messages/folder-watch.js
test/integration/folder-watch.js
test/unit/folder-watch.js

`meta:[folderPath]:displays` is a SET that contains any display id that is
watching the folder. This should be used instead of `folder:[folderPath]`
since that is a list of files in the folder which could be empty if all
files have been removed from the folder.
`meta:[folderPath]:displays` is set during folder watch as part of
`addDisplayToMany`.

Report folder watching correctly

---

src/db/api.js
src/db/redis/datastore.js
test/integration/db-api.js

Concatenating sets results in a watchers list that has duplicate display
ids if a display is watching the folder *and* the file.
This ensures we get unique displayids.
@stulees This is why you were sometimes seeing duplicate *ADD* messages during your testing.

Don't duplicate ADD messages when watching folders

---

src/event-handlers/messages/gcs-file-update.js

Overwriting a file that is trashed is coming through as an update from
PSC because it's an overwrite of an existing file on GCS.
MS needs to add these back into the folder's list of files. It would
have been removed as part of the previous trashing.

Add files to folders when updated

---

src/db/api.js
src/db/redis/datastore.js
src/event-handlers/messages/folder-watch.js
test/integration/folder-watch.js

The current folder file lists include some files they should not. Due to
previous bugs, some files that were trashed and then overwritten with
new versions did not get added back into the folder file list. And in
the opposite case, some files that were trashed are in the folder list.

Reset folder file lists one time

---

src/event-handlers/messages/gcs-file-update.js
test/integration/file-update-handler.js
test/unit/file-update-handler.js

There is currently no way that an offline display will become aware
of a deletion.
With this change, when the display comes back online, it can
submit its watchlist-compare request and handle deletions for any
entries that have version "0".

Update watchlists with version "0" on deletion

---

src/event-handlers/messages/watch.js
test/integration/watch.js

If the display provided a version that doesn't match the version on MS,
then MS provides a token. In this case the watchlist should also be
updated to the correct version so that future watchlist comparisons
match.

Update MS watchlist on version mismatch

---

index.js
package-lock.json
package.json
src/gcs.js
test/integration/connection-state.js

New version uses dependends that avoid using computeMetadata/v1beta1
That endpoint is deprecated on GKE as of 1.12

Upgrade cloud-storage version

---

src/event-handlers/messages/watchlist-compare.js
test/integration/watchlist-compare.js
test/unit/watchlist-compare.js

This will force the displays to request updates on the local files at start up
This is an attempt to fix displays that reported https://github.com/Rise-Vision/rise-launcher-electron/issues/832
Tested on staging by setting up 2 displays (chrome os and electron linux) pointing to [stage environment](https://apps-stage-0.risevision.com/schedules/details/8cfd9db9-2654-4a26-a073-50f88ccebfec?cid=b258739a-527b-438c-b6ec-01057cecdfa2)
Observed logs [here](https://console.cloud.google.com/logs/viewer?organizationId=960705295332&project=messaging-service-180514&minLogLevel=0&expandAll=false&timestamp=2019-12-09T17:45:53.071000000Z&customFacets=&limitCustomFacetWidth=true&interval=NO_LIMIT&resource=container%2Fcluster_name%2Fmessaging-service-stage&scrollTimestamp=2019-12-09T18:01:00.155211303Z&filt …

Always send watchlist from database on watchlist-compare

---

src/event-handlers/messages/clear-local-storage-request.js
test/integration/core-hoook.js

Add `clear-local-storage-request` command. See [design doc](https://docs.google.com/document/d/1v1-IJMKvSqSQ3picvYycLpZwYAQIJqO8TQb5_vwUkHA/edit?usp=sharing).
This improvement was requested in Development Roadmap. It should also help with resolving the "stale content" issues (see [#832](https://github.com/Rise-Vision/rise-launcher-electron/issues/832) and [#829](https://github.com/Rise-Vision/rise-launcher-electron/issues/829)) if they ever occur.
Tested manually on stage. Unit test added.
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release …

Add a command to clear Local Storage

---

.circleci/config.yml
package-lock.json
package.json
src/db/api.js
src/db/redis/datastore.js
src/event-handlers/display-connections.js
src/event-handlers/missed-heartbeat.js
src/google-pubsub/index.js
src/redis-pubsub/index.js
test/integration/missed-heartbeat.js
test/manual/test.js
test/unit/google-pubsub.js

Publishes connection status updates to Google PubSub. This will be picked up by a Google PubSub subscription that calls a Core webhook to update the search documents.
Part of the implementation for [Network Management](https://docs.google.com/document/d/1TIMrr-ujOPaNhJq-PYkn4OLvyytp4eExA1aHVzI93S8/edit)
Unit tests
Integration tests
Manual testing on staging - confirms publish during connection, disconnection, and abandoned connection (missed heartbeat) 
Will merge in the morning and monitor Stackdriver logs for any errors. 
Rollback can be achieved quickly by setting the image back to current.
```
gcloud --project=messaging-service-180514 container clusters get-credentials --zone=us-central1-a messaging-service-prod
kubectl patch deployment messaging-service -p …
```

Publish connection status

---

.gitignore
src/google-pubsub/index.js
test/unit/google-pubsub.js

Prevented publishing to pubsub when displayId has a prefix.
This is a part of the ongoing epic implementation.
Unit tests.
[] Messaging service stage environment is validated to still be working the same as prod
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

Prevented publishing to pubsub when displayId has a prefix

---

.gitignore
index.js
src/event-handlers/messages/folder-watch.js
src/event-handlers/messages/unwatch.js
src/event-handlers/messages/watch.js
src/event-handlers/messages/watchlist-compare.js
src/event-handlers/watch-error.js
src/webhooks/endpoints/direct.js
src/webhooks/endpoints/param-errors.js
src/webhooks/pubsub-connector/post-handler.js
src/websocket/primus-setup.js
test/integration/direct-request-hook.js
test/integration/watch.js

Support for watch/unwatch/folder-watch/watchlist-compare requests via HTTP
This is a part of the ongoing implementation for the current epic.
Integration tests.
[] Messaging service stage environment is validated to still be working the same as prod
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

Support for watch/unwatch/folder-watch/watchlist-compare requests via HTTP

---

src/google-pubsub/index.js
test/unit/google-pubsub.js

Since Players that have their own caching mechanism will not be using
Content Sentinel, the prefix is no longer necessary. Content Sentinel
connections to MS will always be from a Player that does not have any
other connection. Shared Schedules never connect to MS, and older
Players never use Content Sentinel.
See
https://docs.google.com/document/d/1hLXRA5_koBcsZHTIaFdrNxr8WDvD6tI7T6q3CeOpTA8/edit#bookmark=id.92lyimt9h6ol
https://github.com/Rise-Vision/content-sentinel/pull/100
Will test manual connection in staging
[] Messaging service stage environment is validated to still be working the same as prod
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- …

Remove content sentinel prefix handling

---

src/db/redis/datastore.js
src/redis-pubsub/index.js

Point to new master display-ms-redis-primary
Current display-ms-redis-master has no data persistence. Switching to a new deployment is the swiftest way of enabling this as discussed [here](https://docs.google.com/document/d/11ppHdOFX6UAYpiWsbwcp27MH0Sda7wB9QZtKuw8pBlU/edit#).
This work is necessary before enabling display/endpoint validation and banning, to prevent situation where a pods restart, the database reset ( as currently it has no persistence ) and all displays/endpoints are denied access to MS.
All steps were tested in staging.
[x] Messaging service stage environment is validated to still be working the same as prod
To be executed on Thursday or Friday as part of Redis state retention plan.
In case of issues current master node can be configured as persistent with a copy of …

point to redis primary

---

src/webhooks/endpoints/direct.js

doOnIncomingPod doesn't always return a promise so it should not be chained with `.then`
Fixes integration test
unit+integration

Don't expect promise from doOnIncomingPod

---

src/event-handlers/messages/folder-watch.js
src/event-handlers/watch-error.js

Fix missing parameter for direct http WATCH in EMPTYFOLDER case.
Defect [107](https://github.com/Rise-Vision/messaging-service/issues/107)
- Confirmed on staging
[] Messaging service stage environment is validated to still be working the same as prod
- Monday release

Fix missing resp parameter on EMPTYFOLDER

---

index.js
src/webhooks/endpoints/ping.js

Add a basic ping check for viewer networking compatibility checks
[network requirements](https://docs.google.com/document/d/13oYogLEfhNTf3T2eIx0QQ6mt1w8d9rwmIHtzWRppgQw/edit#heading=h.d3725565jynb)
- Confirmed on staging MS websocket connection is still possible
- Confirmed on staging `/messaging/ping` with origin test.risevision.com returns CORS headers and 200

Add ping handler
